localities = [
	"Adugodi",
    "Agara",
    "Akshaya nagar",
    "Anekal",
    "Arakere",
    "Ashoknagar",
    "Attibele",
    "Austin Town",
    "Avalahalli",
    "Banashankari",
    "Banashankari 1st Stage",
    "Banashankari 2nd Stage",
    "Banashankari 3rd Stage",
    "Banaswadi",
    "Bannerghatta Road",
    "Bapujinagar",
    "Basavanagudi",
    "Basaveshwaranagar",
    "Bellandur",
    "Benson Town",
    "Bestamaranahalli",
    "Bidadi",
    "Bidaraguppe",
    "Bommanahalli",
    "Brigade Road",
    "Brookefield",
    "BTM Layout",
    "BTM Layout 1st Stage",
    "BTM Layout 2nd Stage",
    "Byatarayanapura",
    "Chamarajpet",
    "Chandra Layout",
    "Chickpet",
    "Chikkakallasandra",
    "Cox Town",
    "Cubbon Road",
    "Cubbonpet",
    "Cunningham Road",
    "CV Raman Nagar",
    "Dasarahalli",
    "Deepanjalinagar",
    "Devasandra",
    "Dickenson Road",
    "Domlur",
    "Dommasandra",
    "Doorvani Nagar",
    "Electronics City",
    "Frazer Town",
    "Gandhinagar",
    "Ganganagar",
    "Garvebhavipalya",
    "HAL",
    "HAL 2nd Stage",
    "HAL 3rd Stage",
    "Handenahalli",
    "Harogadde",
    "HBR Layout",
    "Hebbal",
    "Hebbal Kempapura",
    "Hegde Nagar",
    "Hennagara",
    "Hennur",
    "Hesaraghatta",
    "Horamavu",
    "Hosakerehalli",
    "Hosur Road",
    "HRBR Layout",
    "HSR Layout",
    "Hulimangala",
    "Indalavadi",
    "Indiranagar",
    "Jakkasandra",
    "Jakkur",
    "Jalahalli",
    "Jayamahal",
    "Jayanagar",
    "Jayanagar 1 Block",
    "Jayanagar 2 Block",
    "Jayanagar 3 Block",
    "Jayanagar 4 Block",
    "Jayanagar 5 Block",
    "Jayanagar 6 Block",
    "Jayanagar 7 Block",
    "Jayanagar 8 Block",
    "Jayanagar 9 Block",
    "Jeevanbhimanagar",
    "Jigani",
    "Jnanabharathi",
    "JP Nagar",
    "JP Nagar 1 Phase",
    "JP Nagar 2 Phase",
    "JP Nagar 3 Phase",
    "JP Nagar 4 Phase",
    "JP Nagar 5 Phase",
    "JP Nagar 6 Phase",
    "JP Nagar 7 Phase",
    "JP Nagar 8 Phase",
    "JP Nagar 9 Phase",
    "K R Market",
    "Kadugodi",
    "Kaggadasapura",
    "Kalkere",
    "Kalyan Nagar",
    "Kamakshipalya",
    "Kammana Halli",
    "Kanakpura Road",
    "Kasturba Road",
    "Kasturi nagar",
    "Kavalbyrasandra",
    "Kempegowda Nagar",
    "Kengeri",
    "KG Road",
    "KH Road",
    "Kodigehalli",
    "Konanakunte",
    "Koramangala",
    "Koramangala 1 Block",
    "Koramangala 2 Block",
    "Koramangala 3 Block",
    "Koramangala 4 Block",
    "Koramangala 5 Block",
    "Koramangala 6 Block",
    "Koramangala 7 Block",
    "Koramangala 8 Block",
    "Koramangala 9 Block",
    "Kothanur",
    "KR Puram",
    "KR Road",
    "Kugur",
    "Kumara Park West",
    "Kumaraswamy Layout",
    "Kundalahalli",
    "Langford Road",
    "Lingarajapuram",
    "Madiwala",
    "Magadi Road",
    "Magrath Road",
    "Mahadevapura",
    "Mahalakshmipuram",
    "Majestic",
    "Mallathahalli",
    "Malleswaram",
    "Marathahalli",
    "Marsur",
    "Mathikere - BEL",
    "Mayasandra",
    "MG Road",
    "Millers Road",
    "Mission Road",
    "Museum Road",
    "Nagarbhavi",
    "Nagawara",
    "Nandini Layout",
    "Narayanapura",
    "Nayandahalli",
    "Neelasandra",
    "Neralur",
    "New BEL Road",
    "New Thippasandra",
    "Old Airport Road",
    "Old Madras Road",
    "Outer Ring Road",
    "Padmanabhanagar",
    "Peenya",
    "Puttenahalli",
    "Race Course Road",
    "Rajajinagar",
    "Rajarajeshwarinagar",
    "Ramamurthy Nagar",
    "Residency Road",
    "Richards Town",
    "Richmond Town",
    "RMV 2nd Stage",
    "RMV Extension",
    "RT Nagar",
    "Sadashivanagar",
    "Sahakaranagar",
    "Samandur",
    "Sampangiramnagar",
    "Sanjay Nagar",
    "Sankey Road",
    "Sarjapur Road",
    "Sarjapura",
    "Seshadripuram",
    "Shantinagar",
    "Shivajinagar",
    "Singasandra",
    "Srirampuram",
    "St.John's Road",
    "St.Marks road",
    "Sunkadakatte",
    "Thammanayakanahalli",
    "Tilaknagar",
    "Ullal Upanagara",
    "Ulsoor",
    "Uttarahalli",
    "Vanakanahalli",
    "Varthur",
    "Vasanthnagar",
    "Victoria Layout",
    "Vidyanagar",
    "Vidyaranyapura",
    "Vijayanagar",
    "Viveknagar",
    "VV Puram",
    "West Of Chord Road",
    "Wheelers Road (Cooke Town)",
    "Whitefield",
    "Wilson Garden",
    "Yadavanahalli",
    "Yelahanka",
    "Yeshwanthpur"
]
