specializations = set([
	"Dentist",
    "General Physician",
    "Ayurveda",
    "Pediatrician",
    "Orthopedist",
    "Gynecologist/obstetrician",
    "Gynecologist",
    "Homeopath",
    "General Surgeon",
    "Cardiologist",
    "Physiotherapist",
    "Dental Surgeon",
    "Orthodontist",
    "Oral And Maxillofacial Surgeon",
    "Dermatologist/cosmetologist",
    "Dermatologist",
    "Ophthalmologist/ Eye Surgeon",
    "Ophthalmologist",
    "Implantologist",
    "Spa",
    "Urologist",
    "Ear-nose-throat (ent) Specialist",
    "Ent/ Otolaryngologist",
    "Diabetologist",
    "Cosmetologist",
    "Psychiatrist",
    "Endodontist",
    "Obstetrician",
    "Periodontist",
    "Radiologist",
    "Prosthodontist",
    "Cosmetic/aesthetic Dentist",
    "Spa Therapist",
    "Dietitian/nutritionist",
    "Pediatric Dentist",
    "Cosmetic/plastic Surgeon",
    "Neurosurgeon",
    "Orthopedic Surgeon",
    "Saloon",
    "Gastroenterologist",
    "Neurologist",
    "Internal Medicine",
    "Wellness",
    "Beautician",
    "Anesthesiologist",
    "Oncologist",
    "Pulmonologist",
    "Infertility Specialist",
    "Psychologist",
    "Hair Transplant Surgeon",
    "Audiologist",
    "Acupuncturist",
    "Speech Therapist",
    "Clinical Physiotherapist",
    "Yoga And Naturopathy",
    "Dentofacial Orthopedist",
    "Oncologist/cancer Specialist",
    "Laparoscopy",
    "Veterinary Physician",
    "Veterinarian",
    "Surgical Oncologist",
    "Alternative Medicine",
    "Allergist/immunologist",
    "Spine Surgeon",
    "Neonatalogist",
    "Nephrologist/renal Specialist",
    "Nephrologist",
    "Consultant Physician",
    "Oral Medicine And Radiology",
    "Head And Neck Surgeon",
    "Clinical Psychologist",
    "Endocrinologist",
    "Orthopedic Physiotherapist",
    "Family Physician",
    "Spine And Pain Specialist",
    "Pediatric Surgeon",
    "General Endocrinologist",
    "Pathologist",
    "General Pathologist",
    "Counselling Psychologist",
    "Andrologist",
    "Sexologist",
    "Cardiothoracic Surgeon",
    "Vascular Surgeon",
    "Sports And Musculoskeletal Physiotherapist",
    "Bariatric Surgeon",
    "Cardiac Surgeon",
    "Trichologist",
    "Psychotherapist",
    "Venereologist",
    "Interventional Cardiologist",
    "Rheumatologist",
    "Neuro Physiotherapist",
    "Reproductive Endocrinologist (infertilty)",
    "Urogynecologist",
    "Gastrointestinal Surgery",
    "Pediatric Dermatologist",
    "Paediatric Intensivist",
    "Geriatric Physiotherapist",
    "Hematologic Oncologist",
    "Gynecologic Oncologist",
    "Dermatosurgeon",
    "Aesthetic Dermatology",
    "Veterinary Surgeon",
    "Sports Medicine Surgeon",
    "Preventive Medicine",
    "Total Joint Surgeon",
    "Radiation Oncologist",
    "Preventive Dentistry",
    "Oral Pathologist",
    "Urological Surgeon",
    "Emergency & Critical Care",
    "Proctologist",
    "Hematologist",
    "Cardiovascular And Pulmonary Physiotherapist",
    "Joint Replacement Surgeon",
    "Unani",
    "Obesity Specialist",
    "Pediatric Cardiologist",
    "Addiction Psychiatrist",
    "Rehab & Physical Medicine Specialist",
    "Occupational Therapist",
    "Cardiothoracic And Vascular Surgeon",
    "Otologist/ Neurotologist",
    "Pediatric Orthopedic Surgeon",
    "Siddha",
    "Rhinologist",
    "Opticians",
    "Optician",
    "Neuropsychiatrist",
    "Geriatrician",
    "Critical Care Medicine",
    "Ultrasonologist",
    "Sonologist",
    "Optometrist",
    "Echocardiologist",
    "Colorectal Surgeon",
    "Sports Nutritionist",
    "Pediatric Urologist",
    "Hepatology",
    "Pediatric Physiotherapist",
    "Aesthetic Medicine",
    "Pediatric Endocrinologist",
    "Hypnotherapist",
    "Geneticist",
    "Educational Psychologist",
    "Dermatopathologist",
    "Adolescent And Child Psychiatrist",
    "Pediatric Neurologist",
    "Emergency Medicine",
    "Sports Medicine Specialist",
    "Sports Medicine Physician",
    "Pediatric Pulmonologist",
    "Hand Surgeon",
    "Chiropractor",
    "Health Psychologist",
    "Pediatric Otolaryngologist",
    "Neuropsychologist",
    "Hepato-biliary-pancreatic",
    "Geriatric Neurologist",
    "Gastroentrology Surgeon",
    "Tcm Physician (traditional Chinese Medicine)",
    "Pediatric Gastroenterologist",
    "Nuclear Medicine Physician",
    "Neonatal Surgeon",
    "Immunodermatologist",
    "Geriatric Psychiatrist",
    "Chronic Liver Specialist",
    "Bone Marrow Transplantation Specialist",
    "Somnologist (sleep Specialist)",
    "Somnologist",
    "Perinatologist",
    "Occupational Psychologist",
    "Surgeon",
    "Cardiac Electrophysiologist",
    "Breast Surgery",
    "Adult Congenital Cardiologist",
    "Toxicologist",
    "Pediatric Rheumatologist",
    "Pediatric Oncologist",
    "Neurointerventional Surgery",
    "Neuroendocrinologist",
    "Intestine Surgeon",
    "Veterinary Toxicologist",
    "Pediatric Ot",
    "Ivf Specialist",
    "Interventional Radiologist",
    "Hiv Specialist",
    "Forensic Psychiatrist",
    "Endocrine Surgeon",
    "Embroyologist",
    "Electrotherapist",
    "Asthma Specialist",
    "Neuro-oncologist",
    "Manual Therapist",
    "Forensic Psychologist",
    "Clinical/biomedical Toxicologist"
])
